---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(viridis)

library(shiny)

data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(borough = neighbourhood_group) %>% 
  select(borough, neighbourhood, stars, price, room_type, lat, long) %>% 
  drop_na(stars)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# selectInput widget
selectInput(
  inputId = "boro_choice", 
  label = h3("Select boro"),
  choices = nyc_airbnb %>% distinct(borough) %>% pull(),
  selected = "Manhattan")


# sliderInput widget
sliderInput(
  "price_range", 
  label = h3("Choose price range"), 
  min = 0, max = 1000, value = c(100, 400))

radioButtons(
  "room_choice", 
  label = h3("Choose room type"),
  choices = c("Private room", "Entire home/apt", "Shared room"), 
  selected = "Entire home/apt")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# renderPrint({ 
#   c(input[["boro_choice"]], input[["boro_choice"]])
# })

# renderText({ 
#   c(input[["boro_choice"]], input[["boro_choice"]])
# })

renderPlotly({ 
  nyc_airbnb %>%
  filter(
    borough == input[["boro_choice"]], 
    price %in% input[["price_range"]][1]:input[["price_range"]][2],
    room_type == input[["room_choice"]] )%>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', stars)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~price, text = ~text_label)
})

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint({ 
  input[["price_range"]]
})
```

### Chart C

```{r}
renderPrint({ 
  input[["room_choice"]]
})
```

